### ISSUE TITLE
Modular Framework: Align subsystem's data plane function pointers on cache line

### ISSUE THREAD

**Issue by nagarahalli** [Linaro/odp#147]
The data plane function pointers in the subsystem's module class need to be aligned at the cache line boundary to avoid loading unwanted data (unwanted for data plane) into the cache line. For ex: consider

typedef ODP_MODULE_CLASS(buffer) {
	odp_module_base_t base;

	odp_api_proto(buffer, buffer_from_event) buffer_from_event;
	odp_api_proto(buffer, buffer_to_event) buffer_to_event;
	odp_api_proto(buffer, buffer_addr) buffer_addr;
	odp_api_proto(buffer, buffer_alloc_multi) buffer_alloc_multi;
	odp_api_proto(buffer, buffer_free_multi) buffer_free_multi;
	odp_api_proto(buffer, buffer_alloc) buffer_alloc;
	odp_api_proto(buffer, buffer_free) buffer_free;
	odp_api_proto(buffer, buffer_size) buffer_size;
	odp_api_proto(buffer, buffer_is_valid) buffer_is_valid;
	odp_api_proto(buffer, buffer_pool) buffer_pool;
	odp_api_proto(buffer, buffer_print) buffer_print;
	odp_api_proto(buffer, buffer_to_u64) buffer_to_u64;
} odp_buffer_module_t;

the function pointer 'buffer_from_event' needs to be aligned on the cache line boundary.

We could also place the control plane functions of the subsystem immediately after 'base' followed by the data plane functions which can be aligned on the cache line boundary.

**Comment by Bill-Fischofer-Linaro** [comment]
I was thinking the same thing after reading Issue #146. Rather than have an active pointer to the module APIs, place the module APIs in the subsystem struct itself so there's no indirection. Align the whole thing on a cache line boundary and order the APIs to keep the most frequently accessed in the first cache line, etc. Something we can discuss in more detail during next week's meetings.

**Comment by Bill-Fischofer-Linaro** [comment]
Closing this as it is unique to Caterpillar, which is now discontinued.
